export type ExecutiveMember = {
  id: number;
  name: string;
  nim: string;
  prodi: string;
  angkatan: string;
  position: string;
  linkedin: string;
  instagram: string;
  image: string;
};

export const EXECUTIVE_YEARS = ["2025"] as const;

export type ExecutiveYear = (typeof EXECUTIVE_YEARS)[number];

export const EXECUTIVES_BY_YEAR: Record<ExecutiveYear, ExecutiveMember[]> = {
  "2025": [
    {
      id: 1,
      name: "Muhammad Haulul Azkiyaa",
      nim: "1302223007",
      prodi: "S1 Rekayasa Perangkat Lunak",
      angkatan: "2022",
      position: "Ketua",
      linkedin: "https://www.linkedin.com/in/haululazkiyaa",
      instagram: "https://www.instagram.com/haululazkiyaa",
      image: "/images/executives/members/2025/om haulul.png",
    },
    {
      id: 2,
      name: "Syahreza Adnan Al Azhar",
      nim: "1302223041",
      prodi: "S1 Rekayasa Perangkat Lunak",
      angkatan: "2022",
      position: "Wakil Ketua",
      linkedin: "https://www.linkedin.com/in/syahreza-adnan/",
      instagram: "https://www.instagram.com/syahreza_adnan_/",
      image: "/images/executives/members/2025/mas wakil.png",
    },
    {
      id: 3,
      name: "Tiara Sabrina",
      nim: "1305223033",
      prodi: "S1 Sains Data",
      angkatan: "2022",
      position: "Sekretaris",
      linkedin: "https://www.linkedin.com/in/tiarasabrina",
      instagram: "https://www.instagram.com/tiarsbrn_",
      image: "/images/executives/members/2025/katiara.png",
    },
    {
      id: 4,
      name: "Zahra Nur Azizah",
      nim: "1305223007",
      prodi: "S1 Sains Data",
      angkatan: "2022",
      position: "Bendahara",
      linkedin: "https://www.linkedin.com/in/zahranurazizah",
      instagram: "https://www.instagram.com/zahranr.azzh",
      image: "/images/executives/members/2025/kazahra.png",
    },
    {
      id: 5,
      name: "Muhammad Emirsyah Makarim",
      nim: "103012300339",
      prodi: "S1 Informatika",
      angkatan: "2023",
      position: "VP internal",
      linkedin: "https://www.linkedin.com/in/muhammad-emirsyah-makarim/",
      instagram: "https://www.instagram.com/emirsyyh/",
      image: "/images/executives/members/2025/pomir.png",
    },
    {
      id: 6,
      name: "Wildan Syukri Niam",
      nim: "1302220005",
      prodi: "S1 Rekayasa Perangkat Lunak",
      angkatan: "2022",
      position: "VP Eksternal",
      linkedin: "https://www.linkedin.com/in/wildanniam/",
      instagram: "https://www.instagram.com/wildanniam_/",
      image: "/images/executives/members/2025/maswil.png",
    },
    {
      id: 7,
      name: "Antonius Simon Pehan Hadjon",
      nim: "1305220083",
      prodi: "S1 Sains Data",
      angkatan: "2022",
      position: "PIC Kompetisi Inovasi",
      linkedin: "https://www.linkedin.com/in/AntoniusSimonPehanHadjon",
      instagram: "https://www.instagram.com/tiarsbrn_",
      image: "/images/executives/members/2025/toni.png",
    },
    {
      id: 8,
      name: "Iksan Oktav Risandy",
      nim: "1302223042",
      prodi: "S1 Rekayasa Perangkat Lunak",
      angkatan: "2022",
      position: "PIC Kompetisi Inovasi",
      linkedin: "linkedin.com/in/iksanrisandy",
      instagram: "instagram.com/ixan.py",
      image: "/images/executives/members/2025/mas iksan.png",
    },
    {
      id: 9,
      name: "Akbar Rizqullah Putra Susanto",
      nim: "103012430043",
      prodi: "S1 Informatika",
      angkatan: "2024",
      position: "PIC Kompetisi Inovasi",
      linkedin: "https://www.linkedin.com/in/akbarrizqullahputrasusanto/",
      instagram: "https://www.instagram.com/akbarrzql/",
      image: "/images/executives/members/2025/akbar.png",
    },
    {
      id: 10,
      name: "Hasnat Ferdiananda",
      nim: "103012430038",
      prodi: "S1 Informatika",
      angkatan: "2024",
      position: "PIC Kompetisi Entrepreneur",
      linkedin: "https://www.linkedin.com/in/hasnatf/",
      instagram: "https://www.instagram.com/hasnat5_/",
      image: "/images/executives/members/2025/hasnat.png",
    },
    {
      id: 11,
      name: "Cahya Rizqi Syah Maulana",
      nim: "1303223012",
      prodi: "S1 Teknologi Informasi",
      angkatan: "2022",
      position: "PIC Kompetisi Entrepreneur",
      linkedin: "https://www.linkedin.com/in/cahya-rizqi-484557151",
      instagram: "https://www.instagram.com/cahya_rizqi",
      image: "/images/executives/members/2025/mas cahya.png",
    },
    {
      id: 12,
      name: "Zuhri Pratisto Basuki",
      nim: "103012300249",
      prodi: "S1 Informatika",
      angkatan: "2023",
      position: "PIC Kompetisi Entrepreneur",
      linkedin: "https://www.linkedin.com/in/zuhripratisto/",
      instagram: "https://www.instagram.com/zuhrii4/",
      image: "/images/executives/members/2025/zuhri.png",
    },
    {
      id: 13,
      name: "Faisal Ihsan Santoso",
      nim: "103032300152",
      prodi: "S1 Teknologi Informasi",
      angkatan: "2023",
      position: "PIC Kompetisi Cyber",
      linkedin: "https://www.linkedin.com/in/faisalsan",
      instagram: "https://www.instagram.com/callmecal.ok/",
      image: "/images/executives/members/2025/faisal.png",
    },
    {
      id: 14,
      name: "Ramadhan Tangguh Defender",
      nim: "103032430003",
      prodi: "S1 Teknologi Informasi",
      angkatan: "2024",
      position: "PIC Kompetisi Cyber",
      linkedin:
        "https://www.linkedin.com/in/ramadhantangguhdefender?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      instagram: "https://www.instagram.com/defen214?igsh=MWg2dWRib3VscGI3bg==",
      image: "/images/executives/members/2025/defen.png",
    },
    {
      id: 15,
      name: "FITYAH BAYODIANSYAH HARAHAP",
      nim: "103022400085",
      prodi: "S1 Rekayasa Perangkat Lunak",
      angkatan: "2024",
      position: "PIC Kompetisi Cyber",
      linkedin:
        "https://www.linkedin.com/in/fityah-bayodiansyah-harahap-578a35279?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      instagram: "https://www.instagram.com/bbayugt.cpp",
      image: "/images/executives/members/2025/bayu.png",
    },
    {
      id: 16,
      name: "Harsya Brahmantyo Wibowo",
      nim: "103032430021",
      prodi: "S1 Teknologi Informasi",
      angkatan: "2024",
      position: "PIC Kompetisi Cyber",
      linkedin: "https://www.linkedin.com/in/harsya-brahmantyo-w/",
      instagram: "https://www.instagram.com/hbtwwwwww/",
      image: "/images/executives/members/2025/harsya.png",
    },
    {
      id: 17,
      name: "Harsya Brahmantyo Wibowo",
      nim: "103032430021",
      prodi: "S1 Sains Data",
      angkatan: "2024",
      position: "PIC Kompetisi Data Mining",
      linkedin: "https://www.linkedin.com/in/ammar-ridho",
      instagram: "https://www.instagram.com/ammarridhojr",
      image: "/images/executives/members/2025/maridojhener.png",
    },
    {
      id: 18,
      name: "Muhammad Karov Ardava Barus",
      nim: "103052300001",
      prodi: "S1 Sains Data",
      angkatan: "2023",
      position: "PIC Kompetisi Data Mining",
      linkedin: "https://www.linkedin.com/in/ardava-barus/",
      instagram: "https://www.instagram.com/rdavaa_/",
      image: "/images/executives/members/2025/ardavuy.png",
    },
    {
      id: 19,
      name: "Wijdanadam Rafifilmi Nadarosula",
      nim: "103052400027",
      prodi: "S1 Sains Data",
      angkatan: "2024",
      position: "PIC Kompetisi Data Mining",
      linkedin: "www.linkedin.com/in/wijdanadam-rafifilmi-nadarosula-89a8b7223",
      instagram: "https://www.instagram.com/wijdan.adam/",
      image: "/images/executives/members/2025/wijdanichbien.png",
    },
    {
      id: 20,
      name: "Radhofan Azizi Ramdhani",
      nim: "1301223058",
      prodi: "S1 Informatika",
      angkatan: "2022",
      position: "PIC Competitive Programming",
      linkedin: "https://www.linkedin.com/in/radhofan-azizi/",
      instagram: "https://www.instagram.com/radho_fun/",
      image: "/images/executives/members/2025/radhofan.png",
    },
    {
      id: 21,
      name: "Alif Wide Ardiansyah",
      nim: "1301223491",
      prodi: "S1 Informatika",
      angkatan: "2022",
      position: "PIC Competitive Programming",
      linkedin: "https://www.linkedin.com/in/alif-wide-ardiansyah/",
      instagram: "https://www.instagram.com/alifwide/",
      image: "/images/executives/members/2025/alif.png",
    },
    {
      id: 22,
      name: "Aisyah Qurrota Aini",
      nim: "103012330374",
      prodi: "S1 Informatika",
      angkatan: "2023",
      position: "PIC Competitive Programming",
      linkedin:
        "https://www.linkedin.com/in/aisyah-qurrota-aini-89ba93289?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      instagram: "https://www.instagram.com/aisyqur?igsh=MWNrdW5neXk1aGNyNA==",
      image: "/images/executives/members/2025/kaaisyqur.png",
    },
    {
      id: 23,
      name: "Arrijal Julfa Arrasyid",
      nim: "103012300217",
      prodi: "S1 Informatika",
      angkatan: "2023",
      position: "Human Capital",
      linkedin: "https://www.linkedin.com/in/arrjello",
      instagram: "https://www.instagram.com/its.jaysss",
      image: "/images/executives/members/2025/masjay.png",
    },
    {
      id: 24,
      name: "Muhammad Rifqi Setiawan",
      nim: "103012330258",
      prodi: "S1 Informatika",
      angkatan: "2023",
      position: "Human Capital",
      linkedin: "https://www.linkedin.com/in/muhammad-rifqi-413713281/",
      instagram: "https://www.instagram.com/rifqi.setiawann/",
      image: "/images/executives/members/2025/rifqi.png",
    },
    {
      id: 25,
      name: "Faisal Surya Saputra",
      nim: "103012330152",
      prodi: "S1 Informatika",
      angkatan: "2023",
      position: "Media",
      linkedin: "https://www.linkedin.com/in/faisalsuryasaputra/",
      instagram: "https://www.instagram.com/fsalsalll_/",
      image: "/images/executives/members/2025/suryosaputroefsal.png",
    },
    {
      id: 26,
      name: "Izzulhaq Mahardika",
      nim: "1305220010",
      prodi: "S1 Sains Data",
      angkatan: "2022",
      position: "Media",
      linkedin: "https://www.linkedin.com/in/dikaizm/",
      instagram: "https://www.instagram.com/dikaizm/",
      image: "/images/executives/members/2025/masdika.png",
    },
    {
      id: 27,
      name: "Reinhard Efraim Situmeang",
      nim: "1302220001",
      prodi: "S1 Rekayasa Perangkat Lunak",
      angkatan: "2022",
      position: "Media",
      linkedin: "https://www.linkedin.com/in/reinhard-situmeang/",
      instagram: "https://www.instagram.com/r3_reinhard/",
      image: "/images/executives/members/2025/masrei.png",
    },
    {
      id: 28,
      name: "Aaron Joseph Karel Daimbani",
      nim: "1302223083",
      prodi: "S1 Rekayasa Perangkat Lunak",
      angkatan: "2022",
      position: "Media",
      linkedin: "https://www.linkedin.com/in/aarondaimbani/",
      instagram:
        "https://www.instagram.com/celest.ron?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==",
      image: "/images/executives/members/2025/aaron.png",
    },
    {
      id: 29,
      name: "Zaky Muhammad Fauzi",
      nim: "103052400064",
      prodi: "S1 Sains Data",
      angkatan: "2024",
      position: "Media",
      linkedin: "https://www.linkedin.com/in/zaky-muhammad-fauzi-7072082b3/",
      instagram: "https://www.instagram.com/za__._____/",
      image: "/images/executives/members/2025/zaky.png",
    },
    {
      id: 30,
      name: "Rahmah Aisyah",
      nim: "103022300014",
      prodi: "S1 Rekayasa Perangkat Lunak",
      angkatan: "2023",
      position: "Partnership",
      linkedin: "https://www.linkedin.com/in/rahmah-aisyah-a53524291/",
      instagram: "https://www.instagram.com/rahmahasyh/",
      image: "/images/executives/members/2025/rahmah.png",
    },
    {
      id: 31,
      name: "Daniandra Prayudisty Ilham",
      nim: "103012300052",
      prodi: "S1 Informatika",
      angkatan: "2023",
      position: "Partnership",
      linkedin:
        "https://www.linkedin.com/in/daniandra-prayudisty-817447233?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
      instagram:
        "https://www.instagram.com/daniandraaa?igsh=NWY3Z21iem9sc250&utm_source=qr",
      image: "/images/executives/members/2025/mas dani.png",
    },
    {
      id: 32,
      name: "Dina Salsabilla",
      nim: "103022300153",
      prodi: "S1 Rekayasa Perangkat Lunak",
      angkatan: "2023",
      position: "Partnership",
      linkedin:
        "https://www.linkedin.com/in/dinasalsabilla?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      instagram:
        "https://www.instagram.com/dnslsabilla?igsh=MWRmc2FnaGh2aDZzZQ%3D%3D&utm_source=qr",
      image: "/images/executives/members/2025/dina.png",
    },
  ],
};
